baseURL = 'https://mhwdvs.github.io/'
languageCode = 'en-au'
title = '(m)att(h)e(w) (d)a(v)i(s)'
theme = 'etch'

[params]
    description = 'Yet another blog'

    copyright = 'Copyright © 2021 Matthew Davis'
