baseURL = 'https://mhwdvs.com/'
languageCode = 'en-au'
title = '(m)att(h)e(w) (d)a(v)i(s)'
theme = 'etch'

[params]
    description = 'Blog of Matthew Davis'
    copyright = '© Matthew Davis 2023'

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "posts"
    title = "posts"
    url = "/posts"
    weight = 10

# tell markdown renderer rawhtml tags are ok
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
